name: Branch Protection

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/branch-protection.yml"

permissions:
  contents: write
  administration: write

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.name,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: ['commitlint']
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true
              },
              allow_force_pushes: false,
              allow_deletions: false,
              restrictions: null
            });
